# Generated by Django 3.1.7 on 2021-08-30 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('participantsNum', models.IntegerField(default=0)),
                ('hasLimitNum', models.BooleanField(default=False, null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('isRequired', models.BooleanField(default=True, null=True)),
                ('CHID', models.CharField(max_length=64, unique=True)),
                ('NQID', models.CharField(max_length=64)),
                ('FOID', models.IntegerField(null=True)),
                ('isMulti', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('participantsNum', models.IntegerField(default=0)),
                ('hasLimitNum', models.BooleanField(default=False, null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('isRequired', models.BooleanField(default=True, null=True)),
                ('CMPID', models.CharField(max_length=64, unique=True)),
                ('NQID', models.CharField(max_length=64)),
                ('correct', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('participantsNum', models.IntegerField(default=0)),
                ('hasLimitNum', models.BooleanField(default=False, null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('isRequired', models.BooleanField(default=True, null=True)),
                ('LOID', models.CharField(max_length=64, unique=True)),
                ('NQID', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOID', models.IntegerField(null=True)),
                ('content', models.TextField()),
                ('selectedNum', models.IntegerField(default=0, null=True)),
                ('score', models.IntegerField(null=True)),
                ('limitNum', models.IntegerField(null=True)),
                ('isCorrect', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('isMale', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StarNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_star', models.IntegerField(default=0, null=True)),
                ('one_star', models.IntegerField(default=0, null=True)),
                ('two_star', models.IntegerField(default=0, null=True)),
                ('three_star', models.IntegerField(default=0, null=True)),
                ('four_star', models.IntegerField(default=0, null=True)),
                ('five_star', models.IntegerField(default=0, null=True)),
                ('CH', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.choicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0, null=True)),
                ('publishTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isClose', models.BooleanField(default=False, null=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('isPublished', models.BooleanField(default=False, null=True)),
                ('showNumbers', models.BooleanField(default=True, null=True)),
                ('hasBranch', models.BooleanField(default=False, null=True)),
                ('recoverNum', models.IntegerField(default=0, null=True)),
                ('limitNum', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('FQID', models.CharField(max_length=64, null=True)),
                ('key', models.CharField(default='panzhita', max_length=64)),
                ('code', models.CharField(default=None, max_length=64, null=True)),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.user')),
            ],
        ),
        migrations.CreateModel(
            name='LOAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('LO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.locationquestion')),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.user')),
            ],
        ),
        migrations.CreateModel(
            name='FillRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fillTime', models.DateTimeField()),
                ('QUEN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.questionnaire')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.user')),
            ],
        ),
        migrations.CreateModel(
            name='CMPAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('CMP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.complition')),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.user')),
            ],
        ),
        migrations.CreateModel(
            name='CHAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField(null=True)),
                ('CH', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.choicequestion')),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.user')),
            ],
        ),
        migrations.CreateModel(
            name='BelongTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(default=-1, null=True)),
                ('question', models.IntegerField(default=-1, null=True)),
                ('order', models.IntegerField(default=-1, null=True)),
                ('QUEN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.questionnaire')),
            ],
        ),
    ]
