# Generated by Django 3.1.7 on 2021-08-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('NAID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('quesNum', models.IntegerField()),
                ('participantsNum', models.IntegerField(default=0)),
                ('limitNum', models.IntegerField(null=True)),
                ('CHID', models.CharField(max_length=64, unique=True)),
                ('NQID', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('quesNum', models.IntegerField()),
                ('participantsNum', models.IntegerField(default=0)),
                ('limitNum', models.IntegerField(null=True)),
                ('CMPID', models.CharField(max_length=64, unique=True)),
                ('NQID', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OID', models.CharField(max_length=64, unique=True)),
                ('NOID', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('selectedNum', models.IntegerField(default=0, null=True)),
                ('score', models.IntegerField()),
                ('limitNum', models.ImageField(upload_to='')),
                ('isCorrect', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('publishTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('answerTime', models.TimeField(null=True)),
                ('isClose', models.BooleanField(default=False, null=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('recoverNum', models.IntegerField(default=0, null=True)),
                ('limitNum', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('FQID', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
