# Generated by Django 3.1.7 on 2021-08-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='OID',
        ),
        migrations.AlterField(
            model_name='option',
            name='NOID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='type',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
