# Generated by Django 3.1.7 on 2021-08-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_auto_20210821_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
