# Generated by Django 3.1.7 on 2021-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_auto_20210821_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='isCorrect',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='limitNum',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
