# Generated by Django 3.1.7 on 2021-08-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0005_choicequestion_foid'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='isMulti',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
