# Generated by Django 3.1.7 on 2021-08-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0007_questionnaire_ispublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='quesNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='complition',
            name='quesNum',
            field=models.IntegerField(null=True),
        ),
    ]
