# Generated by Django 3.1.7 on 2021-08-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0010_auto_20210822_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='CMPID',
            new_name='CMP',
        ),
    ]
