# Generated by Django 3.1.7 on 2021-08-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0011_auto_20210822_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_start', models.IntegerField(default=0, null=True)),
                ('two_start', models.IntegerField(default=0, null=True)),
                ('three_start', models.IntegerField(default=0, null=True)),
                ('four_start', models.IntegerField(default=0, null=True)),
                ('five_start', models.IntegerField(default=0, null=True)),
                ('CH', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.choicequestion')),
            ],
        ),
    ]
