# Generated by Django 3.1.7 on 2021-08-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0012_startnum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartNum',
            new_name='StarNum',
        ),
        migrations.RenameField(
            model_name='starnum',
            old_name='five_start',
            new_name='five_star',
        ),
        migrations.RenameField(
            model_name='starnum',
            old_name='four_start',
            new_name='four_star',
        ),
        migrations.RenameField(
            model_name='starnum',
            old_name='one_start',
            new_name='one_star',
        ),
        migrations.RenameField(
            model_name='starnum',
            old_name='three_start',
            new_name='three_star',
        ),
        migrations.RenameField(
            model_name='starnum',
            old_name='two_start',
            new_name='two_star',
        ),
    ]
