# Generated by Django 3.1.7 on 2021-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0014_starnum_zero_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isMale',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
