# Generated by Django 3.1.7 on 2021-08-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0016_auto_20210822_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.user'),
        ),
    ]
