# Generated by Django 3.1.7 on 2021-08-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0017_questionnaire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='createTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
