# Generated by Django 3.1.7 on 2021-08-26 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0018_questionnaire_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClockRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUID', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('IP', models.CharField(max_length=64)),
                ('highRisk', models.BooleanField()),
                ('hasSymptom', models.BooleanField()),
                ('clockDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMPAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='isRequired',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='complition',
            name='isRequired',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='complition',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='cmpanswer',
            name='CMP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.complition'),
        ),
        migrations.AddField(
            model_name='cmpanswer',
            name='USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.user'),
        ),
        migrations.AddField(
            model_name='chanswer',
            name='CH',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.choicequestion'),
        ),
        migrations.AddField(
            model_name='chanswer',
            name='USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.user'),
        ),
    ]
