# Generated by Django 3.1.7 on 2021-08-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0019_auto_20210826_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('quesNum', models.IntegerField(null=True)),
                ('participantsNum', models.IntegerField(default=0)),
                ('limitNum', models.IntegerField(null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('isRequired', models.BooleanField(default=True, null=True)),
                ('LOID', models.CharField(max_length=64, unique=True)),
                ('NQID', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
