# Generated by Django 3.1.7 on 2021-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0021_auto_20210827_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='showNumbers',
            field=models.BinaryField(default=True, null=True),
        ),
    ]
