# Generated by Django 3.1.7 on 2021-08-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0023_auto_20210827_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fillTime', models.DateTimeField()),
                ('QUEN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.questionnaire')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.user')),
            ],
        ),
    ]
