# Generated by Django 3.1.7 on 2021-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0024_fillrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanswer',
            name='content',
            field=models.IntegerField(),
        ),
    ]
