# Generated by Django 3.1.7 on 2021-08-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0026_auto_20210828_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='limitNum',
            field=models.IntegerField(null=True),
        ),
    ]
