# Generated by Django 3.1.7 on 2021-08-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0027_auto_20210828_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='limitNum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
