# Generated by Django 3.1.7 on 2021-08-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0028_auto_20210828_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
