# Generated by Django 3.1.7 on 2021-08-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0029_auto_20210828_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='quesNum',
        ),
        migrations.RemoveField(
            model_name='complition',
            name='quesNum',
        ),
        migrations.RemoveField(
            model_name='locationquestion',
            name='quesNum',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answerTime',
        ),
    ]
