# Generated by Django 3.1.7 on 2021-08-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0030_auto_20210828_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='limitNum',
            field=models.IntegerField(null=True),
        ),
    ]
