# Generated by Django 3.1.7 on 2021-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0032_auto_20210829_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='code',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='key',
            field=models.CharField(default='panzhita', max_length=64),
        ),
    ]
