# Generated by Django 3.1.7 on 2021-08-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0033_auto_20210829_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='hasBranch',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='BelongTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.option')),
                ('son', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.questionnaire')),
            ],
        ),
    ]
