# Generated by Django 3.1.7 on 2021-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0034_auto_20210829_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='belongto',
            old_name='father',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='belongto',
            name='son',
        ),
        migrations.AddField(
            model_name='belongto',
            name='question',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
