# Generated by Django 3.1.7 on 2021-08-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0035_auto_20210829_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='belongto',
            name='QUEN',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.questionnaire'),
        ),
        migrations.AlterField(
            model_name='belongto',
            name='option',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='belongto',
            name='question',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
