# Generated by Django 3.1.7 on 2021-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0037_belongto_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongto',
            name='order',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
